version: '3.8'

services:
  backend:
    build: ./visualx-backend
    container_name: visualx-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - OPENAI_API_KEY=${key}
    volumes:
      - ./visualx-backend:/app
    working_dir: /app
    command: flask run --host=0.0.0.0 --port=5000
    depends_on:
      - db
    networks:
      - visualx-net

  frontend:
    build: ./visualx-ui-new
    container_name: visualx-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./visualx-ui-new:/app
    working_dir: /app
    command: npm run dev -- --host
    depends_on:
      - backend
    networks:
      - visualx-net

  db:
    image: mysql:8.0
    container_name: visualx-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: visualx_db
      MYSQL_USER: visualx
      MYSQL_PASSWORD: visualxpass
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - visualx-net

volumes:
  dbdata:

networks:
  visualx-net:
